config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  resources :players, only: [:index]
  resources :teams, only: [:index, :new, :create, :destroy]

  root 'teams#index'
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>"}, :default_url => ":style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/ 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :password, presence: true, on: :create, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.page params[:page]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:sign_in][:email])
    if user && user.authenticate(params[:sign_in][:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Invalid email & password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    authorize @team

    if @team.save
      flash[:notice] = "Team saved!"
      redirect_to teams_path
    else
      flash.now[:alert] = "Could not save your team"
      render :new
    end
  end

  def destroy
    @team = Team.find_by_id(params[:id])
    @team.destroy
 
    respond_to do |format|
      format.html {redirect_to teams_path, notice: "#{@team.name} was deleted" }
      format.js
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :logo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<h2> Dodgeball Roster </h2>

app/views/layouts/_navigation.html.erb
<% if current_user %>
  <p>Welcome <%= current_user.email %> </p>
  <p><%= link_to 'Sign out', sign_out_path, method: :delete  %> </p>
<% else %>
  <p><%= link_to 'Sign in', sign_in_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DodgeballRoster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] if flash[:notice] %>
  <%= flash[:alert] if flash[:alert] %>

  <%= render 'layouts/navigation' %>

  <%= yield %>
</body>
</html>

app/views/players/index.html.erb
<h2>Dodgeball Players</h2>

<ul>
  <% @players.each do |player| %>
    <li><%= player.full_name %></li>
  <% end %>  
</ul>

<%= paginate @players %>